#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Tried to get rid of trailing slash but I guess a prefix is needed
# Maybe investigate later
controllers:
  resource: '../src/Controller/'
  type: annotation
  trailing_slash_on_root: false

# Todo
fos_user_security_login:
  path: /user/login
  controller: xxx

fos_user_registration_register:
  path: /user/register
  controller: xxx

fos_user_resetting_request:
  path: /user/reset-request
  controller: xxx

game:
  path: /schedule
  controller: xxx

official_schedule:
  path: /schedule-official
  controller: xxx
